// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC27ieJHq147VaJqW0EuafEYi7wClE4JKw',
    appId: '1:1010007138380:web:e29acd8e5225b2926b94e9',
    messagingSenderId: '1010007138380',
    projectId: 'app-smarti',
    authDomain: 'app-smarti.firebaseapp.com',
    storageBucket: 'app-smarti.firebasestorage.app',
    measurementId: 'G-KXQQF7WSF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr7JvrmePhH4Qp_1Ob1FpoK6_os7mLtKE',
    appId: '1:1010007138380:android:6b168df6e1b62fa56b94e9',
    messagingSenderId: '1010007138380',
    projectId: 'app-smarti',
    storageBucket: 'app-smarti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVJxZW5Dp7yfn9_8HxMBc6jklhVkHa3z4',
    appId: '1:1010007138380:ios:0da7872d0ab525046b94e9',
    messagingSenderId: '1010007138380',
    projectId: 'app-smarti',
    storageBucket: 'app-smarti.firebasestorage.app',
    iosBundleId: 'com.example.appSmarti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVJxZW5Dp7yfn9_8HxMBc6jklhVkHa3z4',
    appId: '1:1010007138380:ios:0da7872d0ab525046b94e9',
    messagingSenderId: '1010007138380',
    projectId: 'app-smarti',
    storageBucket: 'app-smarti.firebasestorage.app',
    iosBundleId: 'com.example.appSmarti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC27ieJHq147VaJqW0EuafEYi7wClE4JKw',
    appId: '1:1010007138380:web:1d026f4f789301ca6b94e9',
    messagingSenderId: '1010007138380',
    projectId: 'app-smarti',
    authDomain: 'app-smarti.firebaseapp.com',
    storageBucket: 'app-smarti.firebasestorage.app',
    measurementId: 'G-SE4BYEEVY5',
  );
}
